// The table itself — one entry per option, in the order `config show` prints them. The
// types, the coercions and the lookups live in `options.ts`; this file is only data.
import type { Option } from "./options.js";
import { LEVELS, WRITE_POLICIES } from "./schema.js";

const THEMES = ["auto", "light", "dark"] as const;

export const OPTIONS: readonly Option[] = [
  {
    name: "port",
    key: "port",
    flag: "--port",
    env: "OPENMASQ_PROXY_PORT",
    file: true,
    kind: "number",
    doc: "loopback port to listen on",
  },
  {
    name: "openai",
    key: "openai",
    flag: "--openai",
    env: "OPENMASQ_UPSTREAM_OPENAI",
    file: true,
    kind: "string",
    doc: "OpenAI-wire upstream origin",
  },
  {
    name: "anthropic",
    key: "anthropic",
    flag: "--anthropic",
    env: "OPENMASQ_UPSTREAM_ANTHROPIC",
    file: true,
    kind: "string",
    doc: "Anthropic-wire upstream origin",
  },
  {
    name: "gemini",
    key: "gemini",
    flag: "--gemini",
    env: "OPENMASQ_UPSTREAM_GEMINI",
    file: true,
    kind: "string",
    doc: "Gemini-wire upstream origin",
  },
  {
    name: "ner",
    key: "nerDir",
    flag: "--ner",
    env: "OPENMASQ_NER_DIR",
    file: true,
    kind: "string",
    doc: "the on-device model's directory",
  },
  {
    name: "rulesOnly",
    key: "rulesOnly",
    flag: "--rules-only",
    file: true,
    kind: "boolean",
    flagSets: true,
    doc: "pattern rules alone, even at a level that asks for the model (an explicit opt-out)",
  },
  {
    name: "mode",
    key: "mode",
    flag: "--mode",
    env: "OPENMASQ_PROXY_MODE",
    file: true,
    kind: "enum",
    values: ["fake", "token"],
    doc: "what the model sees in place of a value",
  },
  {
    name: "keep",
    key: "keep",
    flag: "--keep",
    env: "OPENMASQ_PROXY_KEEP",
    file: true,
    kind: "list",
    doc: "exact values never masked",
  },
  {
    name: "disable",
    key: "disabledKinds",
    flag: "--disable",
    env: "OPENMASQ_PROXY_DISABLED_KINDS",
    file: true,
    kind: "list",
    doc: "kinds left in clear, on top of what the level leaves",
  },
  {
    name: "level",
    key: "level",
    flag: "--level",
    env: "OPENMASQ_PROXY_LEVEL",
    file: true,
    kind: "enum",
    values: LEVELS,
    doc: "which categories are masked",
  },
  {
    name: "always",
    key: "always",
    flag: "--always",
    env: "OPENMASQ_PROXY_ALWAYS",
    file: true,
    kind: "always",
    doc: "terms always masked, whatever the detectors find (value:type)",
  },
  {
    name: "secretsFile",
    key: "secretsFile",
    flag: "--secrets-file",
    file: true,
    kind: "string",
    doc: "a file of exact strings always erased, one per line",
  },
  {
    name: "quiet",
    key: "verbose",
    flag: "--quiet",
    file: true,
    kind: "boolean",
    flagSets: false,
    doc: "no line per request",
  },
  {
    name: "json",
    key: "json",
    flag: "--json",
    file: false,
    kind: "boolean",
    flagSets: true,
    doc: "one JSON object per request on stdout",
  },
  {
    name: "reveal",
    key: "reveal",
    flag: "--reveal",
    file: false,
    kind: "boolean",
    flagSets: true,
    doc: "show the real value behind each substitute, on this terminal or the console page only",
  },
  {
    name: "log",
    key: "logFile",
    flag: "--log",
    file: true,
    kind: "string",
    doc: "where a wrapped run's request lines go",
  },
  {
    name: "mcp",
    key: "mcp",
    flag: "--mcp",
    file: true,
    kind: "boolean",
    flagSets: true,
    doc: "serve /mcp: the declared servers' tools, masked",
  },
  {
    name: "mcpConfig",
    key: "mcpConfig",
    flag: "--mcp-config",
    env: "OPENMASQ_PROXY_MCP_CONFIG",
    file: true,
    kind: "string",
    doc: "the servers file (implies mcp)",
  },
  {
    name: "mcpWrites",
    key: "mcpWrites",
    flag: "--mcp-writes",
    env: "OPENMASQ_PROXY_MCP_WRITES",
    file: true,
    kind: "enum",
    values: WRITE_POLICIES,
    doc: "what a mutating tool call gets",
  },
  {
    name: "mcpAdopt",
    key: "mcpAdopt",
    flag: "--mcp-no-adopt",
    file: true,
    kind: "boolean",
    flagSets: false,
    doc: "take over the wrapped client's own MCP servers",
  },
  {
    name: "console",
    key: "console",
    flag: "--console",
    file: true,
    kind: "boolean",
    flagSets: true,
    doc: "serve the live view at /console",
  },
  {
    name: "consoleReveal",
    key: "consoleReveal",
    flag: "--no-console-reveal",
    env: "OPENMASQ_PROXY_CONSOLE_REVEAL",
    file: true,
    kind: "boolean",
    flagSets: false,
    doc: "the console page carries the real value beside each substitute (its own toggle shows or hides them); off ⇒ substitutes only",
  },
  {
    name: "open",
    key: "open",
    flag: "--open",
    env: "OPENMASQ_PROXY_OPEN",
    file: true,
    kind: "boolean",
    flagSets: true,
    doc: "open the live view in the browser before the tool starts (implies console)",
  },
  {
    name: "splash",
    key: "splash",
    flag: "--no-splash",
    env: "OPENMASQ_PROXY_SPLASH",
    file: true,
    kind: "boolean",
    flagSets: false,
    doc: "play the opening sequence",
  },
  {
    name: "theme",
    key: "theme",
    flag: "--theme",
    env: "OPENMASQ_PROXY_THEME",
    file: true,
    kind: "enum",
    values: THEMES,
    doc: "the ground the terminal paints on",
  },
];
