// Multi-language FIRST-NAME lexicon — the data half of the name gazetteer.
//
// Stored LOWERCASE and UNACCENTED (lookups strip diacritics the same way), so one entry
// "helene" covers Hélène / Helene / HELENE and the accent-dropping OCR of all three.
//
// ⚠️ COLLISION POLICY — read before adding or removing:
// Names that are also common words (pierre, rose, claire, mark, bill, grace…) are
// INCLUDED on purpose: the detector NEVER fires on a lone first name — only on a
// first-name + surname PAIR with capitalization, guards and deny-lists (see
// nameGazetteer.ts). The safety lives in the pairing rule, not in pruning the lexicon.
// What IS excluded: bare particles (van, de, la, ben, abu — never a standalone given),
// entries under 3 characters (the detector floor), and city-collision names (paris).
const PACK = [
  // ── French — classic, modern, regional, compounds' parts ─────────────────────────
  "aaron,abel,adam,adele,adeline,adrien,adrienne,agathe,agnes,aime,aimee,alain,alban,albane,albert,albertine,alex,alexandra,alexandre,alexia,alexis,alice,aline,alix,alphonse,amandine,ambre,amelie,anais,anatole,andre,andrea,andree,ange,angele,angelique,anne,annette,annick,annie,anselme,anthony,antoine,antoinette,apolline,ariane,arlette,armand,armelle,arnaud,arsene,arthur,astrid,athenais,aubin,aude,audrey,augustin,augustine,aurele,aurelie,aurelien,aurore,axel,axelle",
  "baptiste,barbara,barnabe,basile,bastien,beatrice,benedicte,benjamin,benoit,berenice,bernadette,bernard,berthe,bertrand,blaise,blanche,brice,brigitte,bruno,camille,capucine,carine,carole,caroline,casimir,catherine,cecile,cedric,celestin,celestine,celia,celine,cesar,chantal,charles,charline,charlotte,christel,christelle,christian,christiane,christine,christophe,claire,clara,clarisse,claude,claudette,claudine,clement,clementine,clovis,colette,colin,come,constance,constant,coralie,corentin,corinne,cyprien,cyril,cyrille",
  "damien,daniel,daniele,danielle,daphne,david,delphine,denis,denise,didier,dimitri,dominique,donatien,dorian,dorothee,edgar,edith,edmond,edouard,eleonore,eliane,elie,eliott,elisabeth,elise,elodie,eloise,elsa,emeline,emile,emilie,emilien,emma,emmanuel,emmanuelle,enzo,eric,ernest,erwan,esther,etienne,eugene,eugenie,eulalie,eva,evelyne,fabien,fabienne,fabrice,fanny,faustine,felicie,felix,ferdinand,fernand,firmin,flavie,flavien,fleur,flora,florence,florent,florentin,florian,floriane,france,francine,francis,francois,francoise,frederic,frederique",
  "gabin,gabriel,gabrielle,gael,gaelle,gaetan,gaspard,gaston,gautier,genevieve,geoffroy,georges,georgette,gerald,gerard,germain,germaine,gervais,ghislain,ghislaine,gilbert,gilberte,gilles,gisele,gregoire,guillaume,gustave,guy,gwenael,gwenaelle,hadrien,helene,henri,henriette,herve,hilaire,hippolyte,honore,horace,hortense,hubert,hugo,hugues,ines,irene,iris,isabelle,isaure,jacinthe,jacqueline,jacques,jade,janine,jean,jeanne,jeannine,jeremie,jerome,joachim,jocelyn,jocelyne,joel,joelle,johan,jonathan,jordan,joseph,josephine,josette,josiane,jude,jules,julie,julien,julienne,juliette,juste,justine",
  "karine,lambert,laure,laurence,laurent,laurine,lazare,lea,leandre,leon,leonard,leonie,leonore,leopold,liliane,lilou,lily,line,lionel,loic,lorraine,louis,louise,louna,luc,luca,lucas,lucie,lucien,lucienne,lucile,ludivine,ludovic,lydie,madeleine,maelle,maelys,magali,manon,marc,marceau,marcel,marcelle,margaux,margot,marguerite,marianne,marie,marielle,mariette,marina,marine,marion,marius,marlene,marthe,martial,martin,martine,mathias,mathilde,mathis,matthieu,maud,maurice,mauricette,maxence,maxime,maximilien,mehdi,melanie,melissa,michel,michele,micheline,mireille,modeste,monique,morgane,muriel,mylene",
  "nadege,nadine,narcisse,nathalie,nathan,nicolas,nicole,nine,ninon,noe,noel,noelle,noemie,norbert,oceane,octave,odette,odile,olivier,olympe,ombline,ophelie,oscar,pascal,pascale,pascaline,patrice,patricia,patrick,paul,paule,paulette,pauline,perrine,philibert,philippe,philippine,pierre,pierrette,prosper,prudence,quentin,rachel,raoul,raphael,raphaelle,raymond,raymonde,regine,regis,remi,remy,renaud,rene,renee,reine,robert,roberte,rodolphe,roger,roland,rolande,romain,romane,romeo,romuald,rosalie,rose,roseline,roxane",
  "sabine,salome,samuel,sandrine,sarah,sebastien,serge,severin,severine,sidonie,simon,simone,solange,solene,sophie,stanislas,stephane,stephanie,suzanne,suzon,sylvain,sylvaine,sylvestre,sylvie,tanguy,theo,theodore,theophile,therese,thibaud,thibault,thierry,thomas,timothee,titouan,tristan,ulysse,urbain,valentin,valentine,valere,valerie,valery,vanessa,veronique,victoire,victor,victorien,victorine,vincent,violette,virginie,vivien,vivienne,xavier,yann,yannick,yolande,yves,yvette,yvonne,zacharie,zoe",
  // ── English / Anglo ──────────────────────────────────────────────────────────────
  "abigail,adrian,aiden,alan,albert,alfred,alison,amanda,amber,amelia,amy,andrew,angela,angus,anna,annabel,anne,anthony,april,archie,ariel,arnold,arthur,ashley,ashton,aubrey,audrey,austin,ava,barry,beatrice,becky,bella,ben,bernard,bertie,beth,bethany,betty,beverly,bill,billy,blake,bob,bobby,bonnie,brad,bradley,brandon,brenda,brendan,brett,brian,brittany,brooke,bryan,caitlin,caleb,callum,calvin,cameron,candice,carl,carla,carly,carol,caroline,carrie,carter,casey,cassandra,catherine,cathy,cecil,chad,charlene,charlie,charlotte,chelsea,cheryl,chester,chloe,chris,christina,christopher,cindy,claire,clara,clarence,clark,claude,clayton,clifford,clint,clive,cody,colin,connor,cooper,corey,courtney,craig,crystal,curtis,cynthia",
  "daisy,dale,dana,daniel,danielle,danny,daphne,darlene,darren,dave,david,dawn,dean,deborah,debra,dennis,derek,desmond,diana,diane,dolores,don,donald,donna,dora,doris,dorothy,doug,douglas,duncan,dustin,dwight,dylan,earl,eddie,edgar,edith,edmund,edward,edwin,eileen,elaine,eleanor,eliza,elizabeth,ella,ellen,ellie,elliot,elmer,elsie,emily,emma,eric,erica,erin,ernest,ethan,eugene,eunice,evan,evelyn,everett,ezra,faith,felicity,finn,fiona,florence,floyd,frances,frank,franklin,fred,freddie,frederick,gail,gareth,garry,gary,gavin,gemma,gene,geoffrey,george,georgia,gerald,gilbert,gladys,glen,glenda,glenn,gloria,gordon,grace,graham,grant,greg,gregory,gwendolyn",
  "hailey,hank,hannah,harold,harriet,harry,harvey,hazel,heather,hector,heidi,helen,henry,herbert,herman,holly,homer,hope,howard,hugh,hunter,ian,imogen,irene,iris,irving,isaac,isabella,ivan,ivy,jack,jackson,jacob,jade,jake,james,jamie,jane,janet,janice,jasmine,jason,jasper,jean,jeff,jeffrey,jenna,jennifer,jenny,jeremy,jerome,jerry,jesse,jessica,jill,jim,jimmy,joan,joanna,joanne,jodie,joe,joel,john,johnny,jonathan,jordan,joseph,josephine,josh,joshua,joy,joyce,juanita,judith,judy,julia,julian,julie,june,justin,kai,karen,kate,katharine,kathleen,kathryn,kathy,katie,kayla,keith,kelly,kelvin,ken,kendall,kenneth,kevin,kim,kimberly,kirk,kirsten,kurt,kyle",
  "lacey,lance,larry,laura,lauren,laurence,lawrence,leah,lee,leigh,lena,leo,leonard,leroy,leslie,lester,lewis,liam,lillian,lily,linda,lindsay,lisa,lloyd,logan,lois,lola,loren,loretta,lori,lorraine,louie,louis,louise,lucas,lucille,lucy,luke,lydia,lyle,lynn,mabel,mackenzie,madeline,madison,maggie,malcolm,mandy,marcus,margaret,margie,maria,marian,marilyn,marion,marjorie,mark,marlene,marsha,marshall,martha,martin,marvin,mary,mason,matthew,maureen,maurice,max,maxwell,megan,melanie,melinda,melissa,melvin,meredith,mia,michael,michelle,mike,mildred,miles,milton,miranda,mitchell,molly,mona,monica,morgan,murray,myra,myrtle",
  "nancy,naomi,natalie,natasha,nathan,nathaniel,neil,nelson,nicholas,nick,nicole,nigel,nina,noah,nora,norma,norman,olive,oliver,olivia,ollie,opal,oswald,otis,owen,paige,pam,pamela,pat,patricia,patrick,patsy,paula,pauline,pearl,peggy,penelope,penny,percy,perry,pete,peter,phil,philip,phoebe,phyllis,piers,polly,preston,priscilla,rachael,rachel,ralph,randall,randy,raymond,rebecca,reginald,rex,rhonda,richard,rick,ricky,riley,rita,rob,robert,roberta,robin,rodney,roger,roland,ron,ronald,rosemary,ross,roy,ruby,rupert,russell,rusty,ruth,ryan",
  "sabrina,sadie,sally,sam,samantha,samuel,sandra,sandy,sara,sarah,scott,sean,sebastian,selena,seth,shane,shannon,sharon,shaun,sheila,shelby,sheldon,shelley,sherry,shirley,sidney,silas,simon,sonia,sophia,sophie,spencer,stacey,stanley,stella,stephanie,stephen,steve,steven,stewart,stuart,sue,summer,susan,suzanne,sybil,sydney,sylvia,tamara,tammy,tanya,tara,taylor,ted,terence,teresa,terrance,terri,terry,thelma,theodore,thomas,tiffany,tim,timothy,tina,toby,todd,tom,tommy,tony,tracey,tracy,travis,trevor,trisha,troy,tyler,valerie,vanessa,vera,vernon,veronica,vicki,victor,victoria,vincent,viola,violet,virgil,virginia,vivian,wade,wallace,walter,wanda,warren,wayne,wendy,wesley,whitney,wilbur,willa,willard,william,willie,willis,wilma,winifred,winston,wyatt,yvonne,zachary,zoe",
  // ── Spanish / Latin-American ─────────────────────────────────────────────────────
  "adriana,agustin,alejandra,alejandro,alfonso,alfredo,alicia,alonso,alvaro,amalia,amparo,ana,andres,angel,angela,angeles,angelica,anita,antonia,antonio,aranzazu,arturo,asuncion,aurelio,aurora,beatriz,belen,benito,bernardo,blanca,camila,carlos,carlota,carmela,carmen,catalina,cayetano,cecilia,celia,cesar,clara,claudia,concepcion,consuelo,cristina,cristobal,cruz,dario,diego,dolores,domingo,dorotea,eduardo,elena,eloisa,elvira,emilia,emilio,encarnacion,enrique,esperanza,esteban,estela,ester,eugenia,eugenio,eusebio,eva,federico,felipe,fermin,fernanda,fernando,fidel,francisca,francisco,gabriela,gerardo,gloria,gonzalo,graciela,gregorio,guadalupe,guillermo,gustavo",
  "hernan,horacio,ignacio,ines,inmaculada,irene,isabel,isidro,ismael,jacinto,jaime,javier,jesus,joaquin,jorge,jose,josefa,josefina,juan,juana,julio,leticia,lidia,lorena,lorenzo,lourdes,lucia,luciano,luis,luisa,luz,magdalena,manuel,manuela,marcela,marcelo,marcos,margarita,mariano,maribel,maricarmen,mariluz,marisol,marta,mateo,matias,mauricio,maximo,mercedes,miguel,milagros,mireia,montserrat,natalia,nerea,nicolas,nieves,noelia,nuria,octavio,olga,orlando,oscar,pablo,paloma,paola,paquita,patricio,paz,pedro,pilar,rafael,ramiro,ramon,raquel,raul,ricardo,roberto,rocio,rodrigo,rogelio,rosa,rosalia,rosario,ruben,salvador,santiago,sergio,silvia,soledad,sonia,susana,teodoro,teresa,tomas,valeria,vicente,violeta,xavier,yolanda",
  // ── Italian ──────────────────────────────────────────────────────────────────────
  "alberto,aldo,alessandra,alessandro,alessia,alfio,alfredo,amedeo,angelo,annalisa,annamaria,antonella,antonino,arianna,armando,arturo,assunta,attilio,barbara,benedetta,beniamino,bianca,bruna,bruno,carla,carlo,carmela,carmine,caterina,chiara,cinzia,cirillo,claudio,corrado,cosimo,cristian,cristiana,dante,daniela,daniele,dario,davide,domenica,domenico,donatella,edoardo,elena,eleonora,eliana,elisa,elisabetta,emanuela,emanuele,ennio,enrica,enrico,enzo,ermanno,ernesto,ettore,fabio,fabiola,fabrizio,fausto,federica,federico,fernanda,filippo,fiorella,flavia,flavio,franca,francesca,francesco,franco,fulvio,gabriele,gaetano,gennaro,giacomo,giada,gianfranco,gianluca,gianluigi,gianmarco,gianna,gianni,gianpaolo,gilberto,gina,gino,giorgia,giorgio,giovanna,giovanni,giulia,giuliana,giuliano,giulio,giuseppe,giuseppina,graziella,greta,guido",
  "ilaria,ines,irene,isabella,italo,ivana,ivano,lamberto,lara,laura,lavinia,leonardo,letizia,lidia,liliana,livia,livio,lodovico,lorella,lorenza,lorenzo,loretta,luca,lucia,luciana,luciano,lucio,ludovica,luigi,luigia,luisa,manuela,mara,marcella,marcello,marco,margherita,marianna,marina,marino,mario,marisa,marta,martina,marzia,massimiliano,massimo,matilde,mattia,maurizio,mauro,michela,michele,milena,mirella,mirko,monica,nadia,nicola,nicoletta,nino,noemi,orazio,ornella,osvaldo,ottavio,paola,paolo,pasquale,patrizia,patrizio,piera,pierluigi,piero,pietro,pina,pino,raffaele,raffaella,renata,renato,renzo,riccardo,rinaldo,rino,rita,roberta,roberto,rocco,romano,rosanna,rosaria,rosario,rossana,rossella,ruggero,salvatore,sandra,sandro,sara,saverio,sergio,silvana,silvano,silvia,silvio,simona,simone,sonia,stefania,stefano,teresa,tiziana,tiziano,tommaso,tullio,umberto,valentina,valentino,valeria,valerio,vincenza,vincenzo,virginia,vito,vittoria,vittorio,walter",
  // ── German / Austrian / Swiss ────────────────────────────────────────────────────
  "achim,alexander,andrea,andreas,angelika,anja,anke,annegret,annelie,anneliese,annett,ansgar,anton,armin,arnold,astrid,axel,barbel,bastian,beate,benedikt,bernd,bernhard,berthold,bettina,birgit,bjorn,bodo,brigitte,burkhard,carsten,christa,christiane,christoph,claudia,clemens,cornelia,dagmar,detlef,dieter,dietmar,dietrich,dirk,dorothea,eberhard,eckhard,edeltraud,egon,elfriede,elke,ellen,emil,erhard,erika,ernst,erwin,eva,felix,florian,franz,franziska,friedrich,fritz,gabriele,georg,gerd,gerda,gerhard,gerlinde,gernot,gertrud,gisela,gottfried,gregor,gudrun,gunter,gunther,hanna,hannelore,hannes,hans,harald,hartmut,hedwig,heike,heiko,heinrich,heinz,helga,helmut,hendrik,henning,herbert,hermann,hertha,hildegard,holger,horst,hubert,ingeborg,ingo,ingrid,irmgard,jan,jens,joachim,jochen,johann,johanna,johannes,jorg,jurgen,jutta",
  "kai,karin,karl,karlheinz,karsten,katharina,katja,katrin,klaus,konrad,kurt,lars,lena,leonie,lieselotte,lothar,ludwig,lukas,lutz,manfred,manuela,marcus,margarete,margit,margot,marianne,marion,marita,markus,marlies,martina,mathias,matthias,maximilian,meike,michael,michaela,monika,moritz,nadine,nele,niklas,norbert,olaf,ortrud,oskar,otto,paula,peter,petra,philipp,rainer,ralf,regina,reinhard,reinhold,renate,ricarda,roland,rolf,rosemarie,rudi,rudolf,sabine,sandra,sebastian,siegfried,sigrid,silke,simone,sonja,stefan,steffen,susanne,sven,tanja,thea,theodor,thorsten,tilo,tobias,torsten,traudel,udo,ulf,uli,ulrich,ulrike,ursula,uta,ute,uwe,veronika,volker,waldemar,waltraud,werner,wilfried,wilhelm,willi,wolfgang,wolfram",
  // ── Portuguese / Brazilian ───────────────────────────────────────────────────────
  "adao,adriano,afonso,alcides,aline,amanda,americo,anderson,antonio,aparecida,artur,augusto,beatriz,benedito,bernardo,bianca,bruna,bruno,caio,camila,carlos,catarina,celso,cicero,cintia,claudio,conceicao,cristiano,daniela,davi,denise,diego,diogo,duarte,edson,eduarda,eduardo,elisabete,eloa,emanuel,estevao,fabiana,fabiano,fatima,felipe,fernanda,fernando,filipa,filipe,flavia,flavio,francisca,gilberto,gisele,gloria,goncalo,graca,guilherme,gustavo,helder,helena,henrique,hugo,ines,isadora,ivo,jaime,joana,joao,joaquim,jorge,jose,josue,julia,juliana,juliano,laura,leandro,leonor,leticia,livia,lourenco,lucas,luciana,luciano,luis,luisa,luiz,mafalda,maira,manuel,marcelo,marcia,marcio,marco,marcos,margarida,mariana,mario,marisa,mateus,matilde,mauricio,miguel,milton,mirela",
  "natalia,nelson,nuno,otavio,patricia,paulo,pedro,rafael,rafaela,ramon,raquel,regina,reinaldo,renata,renato,ricardo,rodrigo,rogerio,ronaldo,rosa,rui,samuel,sandra,sebastiao,sergio,silvia,simao,sofia,sonia,susana,tatiana,teresa,thiago,tiago,tomas,valdir,valentim,vanda,vania,vasco,vera,vinicius,vitor,vitoria,wagner,wanderley,wilson,zilda",
  // ── Dutch / Flemish ──────────────────────────────────────────────────────────────
  "aart,annemarie,annemiek,antje,arjen,bart,bas,bram,cees,coen,daan,dirk,eelco,elske,esther,femke,floor,floris,geert,gerben,gerrit,gijs,guus,hanneke,harm,henk,hessel,huub,ilse,ineke,jaap,jelle,jeroen,joke,joop,joost,joris,jurgen,kees,koen,lars,lieke,lotte,maaike,maarten,marijke,marloes,mees,mieke,niels,pieter,rens,rik,rinus,roel,ruud,sander,sanne,sjoerd,sven,teun,thijs,tineke,ton,truus,wietse,willem,wim,wouter",
  // ── Nordic (SE/NO/DK/FI/IS) ──────────────────────────────────────────────────────
  "aksel,alva,anders,anitra,anja,ann,annika,are,arne,arvid,asbjorn,asta,astrid,axel,bengt,bente,birger,birgitta,bjarne,bjorn,bo,britt,britta,dagny,ebba,einar,elin,elias,ella,ellen,elsa,emil,erik,erika,esbjorn,eva,finn,freja,frida,frode,geir,gerd,gitte,gorm,greta,gudrun,gunilla,gunnar,gustav,hakan,haldor,halvard,hanne,hans,harald,hedda,helga,helle,henrik,hilde,hjalmar,ida,inga,inge,ingemar,inger,ingrid,ivar,jens,jesper,johanna,jonas,jorgen,kaare,kaisa,kari,karin,kjell,klara,knut,kristian,kristina,lasse,leif,lena,linn,linnea,lisbet,liv,lotta,magnus,maja,malin,marit,mats,mette,mikael,mikko,mona,morten,niklas,nils,njord,oda,oddvar,olaf,olav,ole,olle,oskar,ove,paivi,pekka,pelle,pernille,petter,ragnar,ragnhild,rasmus,roar,rolf,runa,rune,saga,sigrid,signe,sigurd,sindre,siv,soren,stellan,sten,stig,sune,svein,sven,tarja,thor,thora,tor,torbjorn,tore,torsten,trine,trond,tuva,ulf,ulla,unn,vidar,vigdis,viggo,wilma,yngve",
  // ── Polish / Czech / Slovak / Slavic latin ───────────────────────────────────────
  "agnieszka,aleksander,aleksandra,alena,alicja,andrzej,aneta,anezka,antonin,barbora,bartosz,beata,blanka,bogdan,boguslaw,bohumil,bozena,czeslaw,dagmara,danuta,dariusz,dorota,dusan,edyta,elzbieta,ewa,ewelina,filip,franciszek,grazyna,grzegorz,halina,hana,hanna,henryk,ignacy,irena,iva,ivana,iveta,iwona,izabela,jacek,jadwiga,jakub,jana,janusz,jarmila,jaroslav,jaroslaw,jerzy,jindrich,jiri,jitka,joanna,jolanta,josef,jozef,justyna,kamil,kamila,karel,karol,karolina,katarzyna,kazimierz,klara,krystyna,krzysztof,kveta,lech,lenka,leszek,libor,lidia,lubomir,lucie,ludmila,lukasz,maciej,magdalena,malgorzata,marcin,marek,mariusz,marketa,marta,martina,mateusz,michal,mieczyslaw,milan,milena,miloslav,mirek,miroslav,miroslawa,monika,natalia",
  "olga,ondrej,pavel,pavla,pawel,petr,petra,piotr,premysl,przemyslaw,radek,radoslaw,renata,roman,romana,ryszard,slawomir,stanislav,stanislaw,stefania,sylwia,szymon,tadeusz,teresa,tomas,tomasz,urszula,vaclav,vera,veronika,vit,vladimir,vlasta,vojtech,waldemar,wanda,wieslaw,wioletta,witold,wladyslaw,wojciech,zbigniew,zdenek,zdzislaw,zofia,zuzana,zuzanna,zygmunt",
  // ── Russian / Ukrainian / Belarusian (romanized) ─────────────────────────────────
  "aleksei,alexei,anastasia,anatoli,anatoly,andrei,andrey,anna,anton,arkadi,artem,artyom,boris,daria,darya,denis,dmitri,dmitry,ekaterina,elena,evgeni,evgenia,evgeny,fedor,fyodor,galina,gennadi,gennady,georgi,grigori,grigory,igor,ilya,inna,irina,ivan,kirill,konstantin,ksenia,larisa,leonid,lev,lidia,lyudmila,maksim,margarita,marina,maxim,mikhail,nadezhda,natalya,nikita,nikolai,nikolay,oksana,oleg,olga,pavel,polina,pyotr,raisa,roman,ruslan,semyon,sergei,sergey,stanislav,stepan,svetlana,taisia,tamara,tatiana,tatyana,timur,vadim,valentina,valeri,valery,varvara,vasili,vasily,vera,viktor,viktoria,vitali,vitaly,vladimir,vladislav,vyacheslav,yaroslav,yegor,yelena,yevgeni,yulia,yuri,zinaida,bohdan,dmytro,halyna,hanna,iryna,kateryna,mykhailo,mykola,nadiya,natalia,oleksandr,oleksii,olena,ostap,petro,serhii,sofiya,taras,tetiana,volodymyr,yaryna",
  // ── Romanian / Greek (romanized) / Hungarian ─────────────────────────────────────
  "adina,alexandru,anca,andrei,aurel,bogdan,catalin,catalina,cezar,constantin,corina,cosmin,cristi,cristian,daniela,doina,dorin,dragos,dumitru,elena,eugen,florin,gabriel,gheorghe,grigore,ilie,ioan,ioana,ion,ionela,ionut,irina,iulia,iulian,laurentiu,liviu,lucian,marcel,mihai,mihaela,mircea,mirela,nicolae,nicoleta,oana,octavian,ovidiu,radu,raluca,razvan,rodica,sergiu,silviu,sorin,stefan,teodor,tudor,vasile,viorel,viorica,vlad",
  "achilleas,alexandros,anastasios,andreas,angeliki,antonis,apostolos,aristotelis,athanasios,charalambos,christos,dimitra,dimitrios,dimitris,eirini,eleni,elias,evangelia,evangelos,fotini,georgia,georgios,giannis,giorgos,ioanna,ioannis,katerina,konstantina,konstantinos,kostas,kyriaki,kyriakos,lambros,maria,michalis,nikolaos,nikos,panagiota,panagiotis,pavlos,petros,sofia,sotiris,spyros,stavros,stelios,stella,theodora,theodoros,thanasis,vasiliki,vasilis,yannis,zoe",
  "agnes,andras,attila,balazs,bela,csaba,dora,erzsebet,eszter,ferenc,gabor,gergely,gyorgy,gyula,ildiko,imre,istvan,janos,jozsef,judit,katalin,krisztina,lajos,laszlo,levente,marta,matyas,miklos,nandor,orsolya,peter,piroska,reka,sandor,szabolcs,tamas,tibor,timea,zoltan,zsofia,zsolt,zsuzsanna",
  // ── Turkish ──────────────────────────────────────────────────────────────────────
  "ahmet,ali,asli,aylin,ayse,aysel,baris,berk,burak,burcu,bulent,can,cem,cemal,ceren,deniz,derya,dilek,duygu,ebru,ece,elif,emine,emrah,emre,ercan,erdem,erol,esra,fatih,fatma,ferhat,filiz,gamze,gizem,gokhan,gul,gulcan,hakan,halil,hande,hasan,hatice,hulya,husnu,ibrahim,ilker,irem,ismail,kaan,kadir,kemal,kerem,leyla,mehmet,melek,melis,merve,meryem,mesut,metin,murat,mustafa,nazli,necati,nihat,nilufer,nurcan,oguz,okan,onur,osman,ozge,ozlem,pelin,pinar,ramazan,recep,salih,seda,selin,semih,serap,serkan,sevgi,sibel,sinan,songul,suleyman,tarik,tolga,tugba,tuncay,umut,veli,volkan,yasemin,yavuz,yusuf,zehra,zeynep",
  // ── Arabic / Maghreb / Middle-East (romanized) ───────────────────────────────────
  "abdallah,abdel,abdelaziz,abdelkader,abdellah,abdelmajid,abderrahim,abdou,abdoulaye,adel,adil,ahmad,ahmed,aicha,aida,akram,amal,amar,amel,amin,amina,amine,amir,amira,anis,anouar,asma,assia,ayoub,aziz,aziza,badr,bassem,bilal,bochra,boubacar,brahim,chaima,dalila,djamel,driss,fadi,fadila,fairouz,farah,farid,farida,fatiha,fatima,fatma,fawzi,fayssal,fethi,fouad,ghada,habib,hafid,hakim,halima,hamid,hamza,hanane,hania,hassan,hicham,hind,hocine,houda,houssam,ibtissam,idriss,ilham,imane,imad,ismail,jalal,jamal,jamila,karim,karima,khadija,khalid,khaled,laila,lamia,latifa,leila,loubna,mahmoud,majid,malika,mamadou,mariam,maroua,marwa,mehdi,meriem,mohamed,mohammed,mounir,mourad,moussa,mustapha",
  "nabil,nacer,nadia,nadir,naima,najat,najib,nasser,nawal,nazim,nesrine,nizar,nora,noura,nourdine,omar,osama,othmane,ouafa,oumar,rabah,rachid,rachida,radia,rafik,rahma,ramzi,rania,rashid,rayan,reda,rida,rim,rita,saad,sabah,sabrina,said,saida,salah,salem,salim,salima,salma,samia,samir,samira,sana,sarah,sofiane,soraya,souad,tarek,tariq,walid,wassim,yacine,yahia,yasmina,yasmine,yassine,youcef,younes,youssef,zahra,zakaria,zineb,zohra,zoubir",
  // ── Sub-saharan francophone / West Africa ────────────────────────────────────────
  "abdoul,adama,aissatou,alassane,aminata,arouna,awa,bakary,binta,birane,cheikh,coumba,demba,diariatou,djibril,fanta,fatou,fatoumata,habibatou,ibrahima,issa,kadiatou,khady,lamine,mariama,modou,mor,moustapha,ndeye,ousmane,oumou,penda,ramata,rokhaya,sada,salif,sekou,seydou,sidiki,souleymane,tidiane,yacouba",
  // ── Hebrew / Persian ─────────────────────────────────────────────────────────────
  "amit,ariel,avi,aviv,avraham,ayelet,barak,dalia,dana,daniel,david,dov,eitan,eli,eliana,esther,eyal,gal,gideon,gil,hadas,hila,ilan,itai,itzhak,liat,lior,maya,meir,michal,miriam,moran,moshe,naomi,nir,noa,noam,ofer,omer,orit,rachel,rina,ronit,shai,sharon,shira,shlomo,tal,tamar,uri,yael,yair,yaron,yehuda,yonatan,yossi,zeev",
  "abbas,afsaneh,ahmadreza,alireza,amirhossein,arash,ardeshir,azadeh,babak,bahram,behnaz,behrouz,dariush,ehsan,elham,farhad,farideh,farzad,farzaneh,fereshteh,firouz,golnaz,hamed,hamidreza,hossein,kaveh,keyvan,kian,kimia,leila,mahdi,mahnaz,mahsa,mansour,maryam,masoud,mehrdad,mina,minoo,mitra,mohammadreza,mohsen,mojgan,mona,morteza,nasrin,navid,nazanin,neda,niloufar,parisa,parviz,pooya,reza,roya,saeed,sahar,samira,sepideh,setareh,shahin,shahram,shahrzad,shirin,siamak,simin,sohrab,soraya,touraj,vahid,zahra",
  // ── Indian subcontinent ──────────────────────────────────────────────────────────
  "aakash,aarav,aditi,aditya,ajay,akash,akhil,amar,amit,amita,ananya,anil,anita,anjali,ankit,ankita,anuj,anup,arjun,arun,asha,ashok,avinash,bharat,chandra,deepa,deepak,dev,devika,dinesh,divya,ganesh,gaurav,geeta,gita,gopal,harish,ishaan,jaya,jyoti,kabir,kailash,kamala,kamlesh,karan,kavita,kiran,krishna,kumar,lakshmi,lata,madhu,mahesh,manish,manju,manoj,meena,meera,mohan,mukesh,naveen,neha,nikhil,nisha,nitin,pallavi,pankaj,pooja,prakash,pradeep,pranav,praveen,priya,rahul,raj,raja,rajesh,rajiv,raju,rakesh,ram,ramesh,rani,ravi,rekha,ritu,rohan,rohit,sachin,sanjay,sanjiv,santosh,seema,shalini,shankar,shanti,shiva,shreya,siddharth,sneha,sonia,sudha,sujata,sumit,sunil,sunita,suraj,suresh,sushila,swati,uma,umesh,usha,varun,veena,vijay,vikas,vikram,vinay,vinod,vishal,vivek",
  // ── East / South-East Asia (romanized) ───────────────────────────────────────────
  "akira,ayumi,chie,daichi,daisuke,emiko,haruka,haruki,haruto,hideo,hikari,hinata,hiroko,hiroshi,itsuki,kaito,kazuki,kazuko,kazuo,keiko,kenji,kenta,kumiko,mai,makoto,mariko,masako,mei,minato,naoko,naomi,noboru,osamu,ren,rin,riko,ryo,sakura,satoshi,shinji,shota,sota,takashi,takeshi,takumi,tomoko,yoko,yoshiko,yui,yuki,yuko,yuma,yumi,yuna,yuto",
  "bora,chanwoo,dohyun,eunji,eunjung,haeun,hana,hyejin,hyunwoo,jaehyun,jihoon,jimin,jinwoo,jisoo,jiwon,jiyoung,joon,minho,minji,minjun,minseo,miyoung,seojun,seoyeon,siwoo,sohee,soojin,sujin,sunhee,taeyang,yejin,yena,yuna",
  "anh,bao,bich,binh,chau,chi,cuong,dao,duc,dung,duong,giang,hai,han,hanh,hieu,hoa,hoai,hoang,hung,huong,huy,khanh,kim,lan,linh,loan,long,mai,minh,my,nam,nga,ngan,ngoc,nhung,phong,phuong,quan,quang,quynh,son,thang,thanh,thao,thu,thuy,tien,trang,trung,tuan,tung,uyen,van,vinh,xuan,yen",
  "aisyah,agus,andi,ani,bambang,budi,cahya,dewi,dian,dwi,eka,endang,fitri,hadi,hendra,indah,intan,joko,kartika,lestari,maya,mega,nur,nurul,putri,rani,ratna,rina,siti,sri,tri,wahyu,widya,yanti,yudi",
  "cheng,chen,fang,feng,hong,hua,hui,jia,jian,jie,jing,juan,jun,lei,li,lian,liang,lin,ling,mei,ming,na,ping,qiang,qing,rong,rui,shan,tao,ting,wei,wen,xia,xiang,xiao,xin,xiu,yan,yang,ying,yong,yu,yuan,yun,zhen,zhi,zhong",
].join(",");

import { INSEE_FIRST_NAMES } from "./firstNames.insee.data";

/** The lookup set — lowercase, unaccented. Deduped at build (blocks share entries).
 *  The curated multilingual blocks above are UNIONED with the generated INSEE long tail
 *  (`firstNames.insee.data.ts` — ≥100 births in France since 1900, same collision
 *  policy applied mechanically by `scripts/gen-firstnames-insee.ts`). */
export const FIRST_NAMES: ReadonlySet<string> = new Set([
  ...PACK.split(","),
  ...INSEE_FIRST_NAMES,
]);
