// France — real communes with a real postal code + region (matches frGeo REGIONS).
// Several per region so a same-region replacement is usually available. Seed data
// (hand-written); regen with scripts/gen-places.ts from a GeoNames postal dump.
import type { GeoPlace } from "./types";

export const FR_PLACES: GeoPlace[] = [
  { city: "Paris", postal: "75001", region: "Île-de-France" }, { city: "Versailles", postal: "78000", region: "Île-de-France" }, { city: "Nanterre", postal: "92000", region: "Île-de-France" }, { city: "Créteil", postal: "94000", region: "Île-de-France" }, { city: "Melun", postal: "77000", region: "Île-de-France" }, { city: "Cergy", postal: "95000", region: "Île-de-France" },
  { city: "Lyon", postal: "69002", region: "Auvergne-Rhône-Alpes" }, { city: "Grenoble", postal: "38000", region: "Auvergne-Rhône-Alpes" }, { city: "Clermont-Ferrand", postal: "63000", region: "Auvergne-Rhône-Alpes" }, { city: "Annecy", postal: "74000", region: "Auvergne-Rhône-Alpes" }, { city: "Valence", postal: "26000", region: "Auvergne-Rhône-Alpes" }, { city: "Chambéry", postal: "73000", region: "Auvergne-Rhône-Alpes" },
  { city: "Dijon", postal: "21000", region: "Bourgogne-Franche-Comté" }, { city: "Besançon", postal: "25000", region: "Bourgogne-Franche-Comté" }, { city: "Belfort", postal: "90000", region: "Bourgogne-Franche-Comté" }, { city: "Nevers", postal: "58000", region: "Bourgogne-Franche-Comté" }, { city: "Auxerre", postal: "89000", region: "Bourgogne-Franche-Comté" },
  { city: "Rennes", postal: "35000", region: "Bretagne" }, { city: "Brest", postal: "29200", region: "Bretagne" }, { city: "Quimper", postal: "29000", region: "Bretagne" }, { city: "Vannes", postal: "56000", region: "Bretagne" }, { city: "Lorient", postal: "56100", region: "Bretagne" }, { city: "Saint-Brieuc", postal: "22000", region: "Bretagne" },
  { city: "Tours", postal: "37000", region: "Centre-Val de Loire" }, { city: "Orléans", postal: "45000", region: "Centre-Val de Loire" }, { city: "Bourges", postal: "18000", region: "Centre-Val de Loire" }, { city: "Chartres", postal: "28000", region: "Centre-Val de Loire" }, { city: "Blois", postal: "41000", region: "Centre-Val de Loire" },
  { city: "Strasbourg", postal: "67000", region: "Grand Est" }, { city: "Metz", postal: "57000", region: "Grand Est" }, { city: "Nancy", postal: "54000", region: "Grand Est" }, { city: "Reims", postal: "51100", region: "Grand Est" }, { city: "Mulhouse", postal: "68100", region: "Grand Est" }, { city: "Troyes", postal: "10000", region: "Grand Est" },
  { city: "Lille", postal: "59000", region: "Hauts-de-France" }, { city: "Amiens", postal: "80000", region: "Hauts-de-France" }, { city: "Arras", postal: "62000", region: "Hauts-de-France" }, { city: "Beauvais", postal: "60000", region: "Hauts-de-France" }, { city: "Roubaix", postal: "59100", region: "Hauts-de-France" },
  { city: "Rouen", postal: "76000", region: "Normandie" }, { city: "Caen", postal: "14000", region: "Normandie" }, { city: "Le Havre", postal: "76600", region: "Normandie" }, { city: "Évreux", postal: "27000", region: "Normandie" }, { city: "Cherbourg", postal: "50100", region: "Normandie" },
  { city: "Bordeaux", postal: "33000", region: "Nouvelle-Aquitaine" }, { city: "Poitiers", postal: "86000", region: "Nouvelle-Aquitaine" }, { city: "Limoges", postal: "87000", region: "Nouvelle-Aquitaine" }, { city: "Pau", postal: "64000", region: "Nouvelle-Aquitaine" }, { city: "La Rochelle", postal: "17000", region: "Nouvelle-Aquitaine" }, { city: "Niort", postal: "79000", region: "Nouvelle-Aquitaine" }, { city: "Angoulême", postal: "16000", region: "Nouvelle-Aquitaine" },
  { city: "Toulouse", postal: "31000", region: "Occitanie" }, { city: "Montpellier", postal: "34000", region: "Occitanie" }, { city: "Nîmes", postal: "30000", region: "Occitanie" }, { city: "Perpignan", postal: "66000", region: "Occitanie" }, { city: "Carcassonne", postal: "11000", region: "Occitanie" }, { city: "Albi", postal: "81000", region: "Occitanie" }, { city: "Tarbes", postal: "65000", region: "Occitanie" },
  { city: "Nantes", postal: "44000", region: "Pays de la Loire" }, { city: "Angers", postal: "49000", region: "Pays de la Loire" }, { city: "Le Mans", postal: "72000", region: "Pays de la Loire" }, { city: "Laval", postal: "53000", region: "Pays de la Loire" }, { city: "La Roche-sur-Yon", postal: "85000", region: "Pays de la Loire" },
  { city: "Marseille", postal: "13006", region: "Provence-Alpes-Côte d'Azur" }, { city: "Nice", postal: "06000", region: "Provence-Alpes-Côte d'Azur" }, { city: "Toulon", postal: "83000", region: "Provence-Alpes-Côte d'Azur" }, { city: "Avignon", postal: "84000", region: "Provence-Alpes-Côte d'Azur" }, { city: "Aix-en-Provence", postal: "13100", region: "Provence-Alpes-Côte d'Azur" }, { city: "Gap", postal: "05000", region: "Provence-Alpes-Côte d'Azur" },
  { city: "Ajaccio", postal: "20000", region: "Corse" }, { city: "Bastia", postal: "20200", region: "Corse" },
];
