/* GENERATED by scripts/build-console.mjs from page/ — do not edit.
   The page's decisions live in TypeScript so they can be typed and tested; this is only
   their browser form. Edit page/*.ts and re-run the script. */
"use strict";
var openmasqConsole = (() => {
  var __defProp = Object.defineProperty;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

  // src/features/console/page/main.ts
  var main_exports = {};
  __export(main_exports, {
    exportDocument: () => exportDocument,
    exportFilename: () => exportFilename,
    exportableEvent: () => exportableEvent,
    mayReveal: () => mayReveal
  });

  // src/features/console/page/reveal.ts
  var mayReveal = (sent, shown) => sent === true && shown === true;
  function exportableEvent(raw, allowed) {
    if (!raw) return {};
    const out = structuredClone(raw);
    if (!allowed) for (const item of out.items ?? []) delete item.real;
    return out;
  }
  function exportDocument(events, opts) {
    const allowed = mayReveal(opts.sent, opts.shown);
    return {
      app: "openmasq-proxy",
      exported: (opts.now ?? /* @__PURE__ */ new Date()).toISOString(),
      reveal: allowed,
      events: events.map((e) => exportableEvent(e, allowed))
    };
  }
  var exportFilename = (now = /* @__PURE__ */ new Date()) => `openmasq-journal-${now.toISOString().slice(0, 19).replace(/[:T]/g, "-")}.json`;
  return __toCommonJS(main_exports);
})();
