#!/usr/bin/env node
/**
 * `src/features/console/app.js`, bundled from the page's own TypeScript (`page/`).
 *
 * The page used to be one asset with eight hundred lines of `<script>` in it, which meant
 * none of that logic could be imported, typed or tested — including the rule deciding when a
 * real value may be shown. This is the door out: the page keeps its markup and its CSS as an
 * asset (they are the design kit, and diffing them against it is the point), while everything
 * that DECIDES something becomes modules under `page/`.
 *
 * Generated INTO `src/`, deliberately: `tokens.css` beside it is generated the same way, for
 * the same reason — `dev` runs straight off `src` with no build, so an artefact the page
 * needs has to be there too. The drift that invites is answered the same way as well, by a
 * test that re-runs this with `--check` (`console.test.ts`).
 *
 *   node scripts/build-console.mjs            # write
 *   node scripts/build-console.mjs --check    # exit 1 on drift (the test uses this)
 *
 * NO React here yet, and no framework of any kind: this step only has to exist and be
 * trusted. What it bundles today is plain modules; what it bundles next is the same pipeline
 * with a renderer on top.
 */
import { build } from "esbuild";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const CONSOLE = join(here, "..", "src", "features", "console");
const ENTRY = join(CONSOLE, "page", "main.ts");
const OUT = join(CONSOLE, "app.js");

const HEADER = `/* GENERATED by scripts/build-console.mjs from page/ — do not edit.
   The page's decisions live in TypeScript so they can be typed and tested; this is only
   their browser form. Edit page/*.ts and re-run the script. */\n`;

/**
 * One IIFE, no imports at runtime: the page is served from a token-gated route and must stay
 * self-contained — it fetches nothing, from anywhere. `es2020` is the floor every browser
 * that can open a localhost page clears, and it keeps the output readable enough to audit.
 */
async function bundle() {
  const out = await build({
    entryPoints: [ENTRY],
    // ⚠️ PINNED, and not for tidiness: esbuild writes each module's path into the bundle as a
    // comment, RELATIVE to the working directory. Without this the same sources produce a
    // different file from the repo root than from `apps/proxy`, so `--check` called one way
    // contradicts a build done the other — which is exactly how a committed artefact and its
    // guard start disagreeing. The bundle must depend on its inputs and nothing else.
    absWorkingDir: join(here, ".."),
    bundle: true,
    format: "iife",
    globalName: "openmasqConsole",
    target: "es2020",
    platform: "browser",
    // `source` first: `@openmasq/ui/tooltip` then resolves to that package's TypeScript
    // rather than its `dist`, so this bundle depends on sources alone and no build order.
    conditions: ["source", "import", "default"],
    write: false,
    legalComments: "none",
  });
  return HEADER + (out.outputFiles[0]?.text ?? "");
}

const next = await bundle();
if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(OUT, "utf8");
  } catch {
    /* missing counts as drift */
  }
  if (current !== next) {
    console.error(`${OUT} is stale.\nRun: pnpm --filter @openmasq/proxy console:build`);
    process.exit(1);
  }
  console.log("console bundle up to date.");
} else {
  writeFileSync(OUT, next);
  console.log(`wrote ${OUT} (${(next.length / 1024).toFixed(1)} kB)`);
}
